export const themes = {
  midnight: {
    name: 'Midnight Workshop',
    bg: 'bg-slate-900',
    surface: 'bg-slate-800',
    surfaceHover: 'hover:bg-slate-700',
    primary: 'bg-blue-500',
    primaryHover: 'hover:bg-blue-600',
    primaryText: 'text-white',
    accent: 'bg-orange-500',
    text: 'text-slate-100',
    textSecondary: 'text-slate-400',
    border: 'border-slate-700',
    success: 'bg-green-500',
    warning: 'bg-yellow-500',
    danger: 'bg-red-500',
    input: 'bg-slate-700 text-slate-100 border-slate-600'
  },
  carbon: {
    name: 'Carbon Steel',
    bg: 'bg-zinc-900',
    surface: 'bg-zinc-800',
    surfaceHover: 'hover:bg-zinc-700',
    primary: 'bg-cyan-500',
    primaryHover: 'hover:bg-cyan-600',
    primaryText: 'text-white',
    accent: 'bg-purple-500',
    text: 'text-zinc-50',
    textSecondary: 'text-zinc-400',
    border: 'border-zinc-700',
    success: 'bg-green-500',
    warning: 'bg-yellow-400',
    danger: 'bg-rose-500',
    input: 'bg-zinc-700 text-zinc-100 border-zinc-600'
  },
  industrial: {
    name: 'Industrial Blue',
    bg: 'bg-blue-950',
    surface: 'bg-blue-900',
    surfaceHover: 'hover:bg-blue-800',
    primary: 'bg-blue-500',
    primaryHover: 'hover:bg-blue-600',
    primaryText: 'text-white',
    accent: 'bg-orange-500',
    text: 'text-blue-50',
    textSecondary: 'text-blue-300',
    border: 'border-blue-800',
    success: 'bg-green-600',
    warning: 'bg-yellow-500',
    danger: 'bg-red-600',
    input: 'bg-blue-800 text-blue-100 border-blue-700'
  },
  light: {
    name: 'Light Pro',
    bg: 'bg-slate-50',
    surface: 'bg-white',
    surfaceHover: 'hover:bg-slate-100',
    primary: 'bg-blue-600',
    primaryHover: 'hover:bg-blue-700',
    primaryText: 'text-white',
    accent: 'bg-amber-500',
    text: 'text-slate-900',
    textSecondary: 'text-slate-600',
    border: 'border-slate-200',
    success: 'bg-green-600',
    warning: 'bg-amber-600',
    danger: 'bg-red-600',
    input: 'bg-white text-slate-900 border-slate-300'
  }
}